// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thbkgqozqemsgpbbceff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYmtncW96cWVtc2dwYmJjZWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDEzNzMsImV4cCI6MjA2MjY3NzM3M30.NosObkr3Wz84YSTgnHffOxeXHIJ_vZ7pmHa5v_Di8dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);